version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing NVM"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - echo "Installing Node.js"
      - nvm install 16
      - node -v
      - echo "Installing NPM packages"
      - npm install
      - echo "Installing dependencies..."
      - npm install -g eslint@8.26.0
      - npm install dotenv@16.0.0 
      - npm install form-data@4.0.0 lodash@4.17.21 moment@2.29.1 
      - npm install next@13.0.1 
      - npm install react@18.2.0 
      - npm install react-content-loader@6.2.0 react-device-detect@2.2.2 react-dom@18.2.0 react-grid-system@8.1.6 react-lodash@0.1.2 react-paginate@8.1.4 react-select@5.6.1 
  build:
    commands:
      - echo "Building the application"
      - npm run build
  post_build:
    commands:
      - echo "Application build completed successfully"
      - npm run start
