version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt-get update
      - sudo apt-get -y install build-essential libssl-dev curl
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
      - nvm install 16.13.1
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  post_build:
    commands:
      - echo "Starting server..."
      - node server.js
